image: node:7.8.0
before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential
  - npm install -g @angular/cli


build:
  script:
    - npm install
    - ng bundle

test:
  services:
    - docker.elastic.co/elasticsearch/elasticsearch:5.3.0
  script:
    - npm install --dev
    - npm test
    - npm e2e
