image: node:7.8.0
before_script:
  - npm install -g @angular/cli

build:
  script:
    - npm install

e2e_test:
  services:
    - docker.elastic.co/elasticsearch/elasticsearch:5.3.0
  before_script:
  # install chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update
    - apt-get install -y google-chrome-stable xvfb
    - rm -rf /var/lib/apt/lists/*

    # xvfb
    - export DISPLAY=:99.0
    - Xvfb -ac $DISPLAY &

    # give webserver some time to start
    - sleep 3
  script:
    - npm install --dev
    - ng e2e
