image: node:7.8.0
before_script:
  - npm install -g @angular/cli


build:
  script:
    - npm install

test:
  services:
    - docker.elastic.co/elasticsearch/elasticsearch:5.3.0
  script:
    - npm install --dev
    - ng e2e
