image: node:7.8.0

cache:
  paths:
    - node_modules/

build:
  before_script:
    - npm install -g @angular/cli
  script:
    - npm install

e2e_test:
  services:
    - docker.elastic.co/elasticsearch/elasticsearch:5.3.0
  before_script:
    - npm install -g @angular/cli
    - npm install --dev
    # install chrome
    - apt-get update
    - apt-get install -y chromium-browser xvfb
    - rm -rf /var/lib/apt/lists/*

    # xvfb
    - export DISPLAY=:99.0
    - Xvfb -ac $DISPLAY &

  script:
    - ng e2e
