image: node:7.8.0

cache:
  paths:
    - ~/.npm/

build:
  before_script:
    - npm install -g @angular/cli
  script:
    - npm install

e2e_test:
  before_script:
    - npm install -g @angular/cli
    - npm install
    - npm install --only=dev

    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update
    - apt-get install -y -qq google-chrome-stable xvfb default-jre
    - rm -rf /var/lib/apt/lists/*

    - export DISPLAY=:99.0
    - Xvfb -ac $DISPLAY &
    - sleep 10
  script:
    - ng e2e
