---
sudo: required

services:
  - docker

before_install:
  # Update Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose version
  # Create elasticsearch containers and testcontainer and start them
  - sudo sysctl -w vm.max_map_count=262144
  - docker-compose -f testingEnv/docker-compose.yml up -d
  - sleep 20

  # Install dependencies
  - docker exec -it test npm install
  - docker exec -it test npm install --only=dev

  # Load test data
  - docker exec -it test bash testingEnv/data2es.sh

script:
  - docker exec -it test getent hosts elasticsearch
  - docker exec -it test curl http://elasticsearch:9200
  - docker exec -it test ng e2e

after_success:
  - docker exec -it test ng build --prod
  - docker build -t heckenmann/esmt:$TRAVIS_JOB_ID .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push heckenmann/esmt;
    fi

after_script:
  - docker-compose -f testingEnv/docker-compose.yml down
