---
sudo: required

language: node_js

node_js:
  - "7"

services:
  - docker

before_install:
  - npm install -g @angular/cli
  - npm install
  - npm install --only=dev

script:
  - ng e2e && ng build --prod
