---
sudo: required

services:
  - docker

before_install:
  # Update Docker
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  # Install docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose version
  # Create elasticsearch containers and testcontainer and start them
  - docker-compose -f testingEnv/docker-compose.yml up -d
  - sleep 20

  # Install dependencies
  - docker exec -it test npm install
  - docker exec -it test npm install --only=dev

script:
  - docker exec -it test getent hosts elasticsearch
  - docker exec -it test curl http://elasticsearch:9200
  - docker exec -it test ng e2e

after_success:
  - docker exec -it test ng build --prod
  - docker build -t heckenmann/esmt:$TRAVIS_JOB_ID .

after_script:
  - docker-compose -f testingEnv/docker-compose.yml down
