---
version: '3'
services:
  elasticsearch00:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
    environment:
      - node.name=elasticsearch00
      - discovery.zen.ping.unicast.hosts=elasticsearch00,elasticsearch01,elasticsearch02
      - discovery.zen.minimum_master_nodes=2
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
  elasticsearch01:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
    links:
      - elasticsearch00
    environment:
      - node.name=elasticsearch01
      - discovery.zen.ping.unicast.hosts=elasticsearch00,elasticsearch01,elasticsearch02
      - discovery.zen.minimum_master_nodes=2
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
  elasticsearch02:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.3.0"
    links:
      - elasticsearch00
      - elasticsearch01
    environment:
      - node.name=elasticsearch02
      - discovery.zen.ping.unicast.hosts=elasticsearch00,elasticsearch01,elasticsearch02
      - discovery.zen.minimum_master_nodes=2
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - xpack.security.enabled=false
